# Generated by Django 5.0 on 2024-12-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='product',
        ),
    ]
