# Generated by Django 5.1.4 on 2024-12-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_buy'),
        ('store', '0007_buy_product'),
    ]

    operations = [
    ]
