# Generated by Django 5.1.4 on 2024-12-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_0002_buy_0007_buy_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('Sum', 'Sum'), ('Rub', 'Rub'), ('$', '$')], default='Sum', max_length=10),
        ),
    ]
